apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-dev
data:
  index.html: |
      <H1> Hello Dev ENV </H1>
---      
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-prod
data:
  index.html: |
      <H1> Hello PROD ENV </H1>

---
kind: Pod 
apiVersion: v1 
metadata:
  name: cm-pod-ex1 
spec:
  containers:
    - name: cm-pod-cont
      image: nginx
      ports:
        - containerPort: 80
      ## to use ConfigMap as files in a volume
      volumeMounts:
         - name: html-from-cm
           mountPath: /usr/share/nginx/html/
           readOnly: true
  volumes:
   - name: html-from-cm
     configMap:
       name: nginx-dev 
